script: make

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
 - sudo apt-get update -qq
 - sudo apt-get install gcc-4.8;
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20;
 - g++ --version;
 - sudo apt-get install -qq libnl-3-dev
 - sudo apt-get install -qq libnl-route-3-dev

# Runtime dependencies
# - sudo apt-get install -qq libnl-3-200
# - sudo apt-get install -qq libnl-route-3-200
# - sudo apt-get install -qq libnl-genl-3-200

install: true
